### ISSUE TITLE
Minor HTML issue

### ISSUE THREAD

**Issue by ray10k** [voodooattack/when-ts#2]
https://github.com/voodooattack/when-ts/blob/555f5665650d1f8f0dca9498439fd3a5f73226f5/src/stateMachine.ts#L74
The < S > at the end of the line gets interpreted as a strikethrough tag, leading to the documentation being crossed out from here on out:
https://voodooattack.github.io/when-ts/classes/statemachine.html

**Comment by voodooattack** [comment]
Thank you for reporting this. I've made a bug report.

**Comment by voodooattack** [comment]
Closing this now since the root issue is an external tool.
